
services:
  alfurquan-api:
    container_name: alfurquan-api
    build: ./
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - alf-network
networks:
  alf-network:
    external: true
